project_name: autobot

builds:
  -
    id: autobot
    binary: autobot
    main: server/main.go
    before:
      hooks:
      - go mod download
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - 386
      - amd64
    ignore:
      - goos: darwin
        goarch: 386
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
  -
    id: plugin-slack
    binary: plugin-slack
    main: ./plugins/plugin-slack/main.go
    before:
      hooks:
      - go mod download
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - 386
      - amd64
    ignore:
      - goos: darwin
        goarch: 386
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on

release:
  draft: false

snapshot:
  name_template: "{{.Tag}}"

checksum:
  name_template: "autobot_checksums.txt"

archives:
  -
    id: autobot
    builds:
    - autobot
    name_template: "autobot_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  -
    id: plugin-slack
    builds:
    - plugin-slack
    name_template: "plugin_slack_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

dockers:
  -
    goos: linux
    goarch: amd64
    binaries:
      - autobot
    image_templates:
     - "andersnormal/{{.ProjectName}}:latest"
     - "andersnormal/{{.ProjectName}}:{{ .Tag }}"
     - "andersnormal/{{.ProjectName}}"
  -
    goos: linux
    goarch: amd64
    binaries:
      - plugin-slack
    image_templates:
     - "andersnormal/plugin-slack:latest"
     - "andersnormal/plugin-slack:{{ .Tag }}"
     - "andersnormal/plugin-slack"
