project_name: autobot

env:
  - CGO_ENABLED=0
  - GO111MODULE=on
before:
  hooks:
    - go mod download

builds:
  -
    id: autobot
    binary: autobot
    main: server/main.go
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - 386
      - amd64
    ignore:
      - goos: darwin
        goarch: 386
  -
    id: plugin-slack
    binary: autobot-plugin-slack
    main: ./plugins/plugin-slack/main.go
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - 386
      - amd64
    ignore:
      - goos: darwin
        goarch: 386

release:
  draft: false

snapshot:
  name_template: "{{.Tag}}"

checksum:
  name_template: "autobot_checksums.txt"

archives:
  -
    id: autobot
    builds:
    - autobot
    name_template: "autobot_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  -
    id: plugin-slack
    builds:
    - plugin-slack
    name_template: "plugin_slack_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

dockers:
  -
    dockerfile: Dockerfile
    goos: linux
    goarch: amd64
    binaries:
      - autobot
    image_templates:
     - "andersnormal/{{.ProjectName}}:latest"
     - "andersnormal/{{.ProjectName}}:{{ .Tag }}"
     - "andersnormal/{{.ProjectName}}"
  -
    dockerfile: plugins/plugin-slack/Dockerfile
    goos: linux
    goarch: amd64
    binaries:
      - autobot-plugin-slack
    image_templates:
     - "andersnormal/{{.ProjectName}}-plugin-slack:latest"
     - "andersnormal/{{.ProjectName}}-plugin-slack:{{ .Tag }}"
     - "andersnormal/{{.ProjectName}}-plugin-slack"
