project_name: autobot

builds:
  -
    id: autobot
    binary: autobot
    main: server/main.go
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - 386
      - amd64
    ignore:
      - goos: darwin
        goarch: 386
    env:
      - CGO_ENABLED=0
  -
    id: plugin-slack
    binary: plugin-slack
    main: ./plugins/plugin-slack/main.go
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - 386
      - amd64
    ignore:
      - goos: darwin
        goarch: 386
    env:
      - CGO_ENABLED=0

release:
  draft: false

snapshot:
  name_template: "{{.Tag}}"

checksum:
  name_template: "autobot_checksums.txt"

archives:
  -
    id: autobot
    builds:
    - autobot
  -
    id: plugin-slack
    builds:
    - plugin-slack

dockers:
  -
    goos: linux
    goarch: amd64
    binaries:
      - autobot
  - image_templates:
    - "andersnormal/{{.ProjectName}}:latest"
    - "andersnormal/{{.ProjectName}}:{{ .Tag }}"
    - "andersnormal/{{.ProjectName}}"
