version: 1
author: Sebastian Döll <sebastian@andersnormal.us>
project: autobot
tasks:
  proto:
    desc: building the proto
    cmds:
      - protoc --go_out=plugins=grpc:./proto --proto_path=proto proto/*.proto
  build/server:
    desc: building the server
    cmds:
      - cd server && go build
  build/ci:
    desc: building the cli
    cmds:
      - cd cli && go build
  badge:
    desc: update badges
    cmds:
      - gopherbadger -md "README.md" -png=false
