version: "3.7"

services:
  controller:
    image: andersnormal/autobot
    ports:
      - "8222:8222"
      - "8223:8223"
      - "4222:4222"
      - "4223:4223"
    command: ["--verbose", "--debug"]
    networks:
      - autobot

  slack:
    image: andersnormal/autobot-plugin-slack
    env_file: .env
    restart: always
    depends_on:
      - controller
    networks:
      - autobot

  hello:
    image: andersnormal/autobot-plugin-hello-world
    env_file: .env
    restart: always
    depends_on:
      - slack
    networks:
      - autobot

networks:
  autobot:
