version: "3.7"

services:
  controller:
    image: andersnormal/autobot
    ports:
      - "8222:8222"
      - "8223:8223"
      - "4222:4222"
      - "4223:4223"
    command: ["--verbose", "--debug"]
    networks:
      - overlay

  slack:
    image: andersnormal/autobot-plugin-slack
    env_file: .env
    # environment:
    #   SLACK_TOKEN:
    #   AUTOBOT_CLUSTER_ID: 'test-autobot-cluster'
    #   AUTOBOT_CLUSTER_URL: 'nats://controller:4222'
    #   AUTOBOT_CHANNEL_DISCOVERY: 'slack'
    networks:
      - overlay

networks:
  overlay:
