name: Test & Build

on:
  push:
    branches:
    - master
    - release/*
  pull_request:
    branches:
    - master

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Setup go
      uses: actions/setup-go@v1
      with:
        go-version: '1.13.1'
    - name: Run Static Checks
      run: GO111MODULE=off go get honnef.co/go/tools/cmd/staticcheck && staticcheck ./...
    - name: Run Tests
      run: go test -race -mod vendor -v ./...
    - name: Slack
      uses: rtCamp/action-slack-notify@master
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
