on:
  push:
    tags:
      - 'v*'
      
name: Release
jobs:
 test:
 
    name: Go ${{ matrix.go }} Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.12' ]
    steps:
    
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Setup go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}

    - name: Run Tests
      run: go test -race -mod vendor -v ./...
      
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [ test ]
    steps:
    - name: Check out code
      uses: actions/checkout@master
    - name: Docker Login
      uses: actions/docker/login@master
      env:
        DOCKER_USERNAME: ${{ secrets.GITHUB_DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.GITHUB_DOCKER_PASSWORD }}
    - name: goreleaser
      uses: docker://goreleaser/goreleaser
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: release
      if: success()
